comment/urls.py
from django.urls import path

from comment.views import comment_create

app_name = "comment"

urlpatterns = [
    path("create", comment_create, name="create"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

from lib.views import IndexTemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipe/", include("recipe.urls", namespace="recipe")),
    path("comment/", include("comment.urls", namespace="comment")),
    path("staffroom/", include("staffroom.urls", namespace="staffroom")),
    path("login", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout", LogoutView.as_view(template_name="logout.html"), name="logout"),
    path("", IndexTemplateView.as_view(), name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/urls.py
from django.urls import path

from recipe.views import RecipeDetailView, RecipeListView

app_name = "recipe"

urlpatterns = [
    path("", RecipeListView.as_view(), name="index"),
    path("<int:pk>", RecipeDetailView.as_view(), name="detail"),
]

comment/models.py
from django.db import models

from recipe.models import Recipe


class Comment(models.Model):
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, default=None, null=True)

recipe/models.py
from django.contrib.auth.models import User
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class Recipe(models.Model):
    title = models.CharField(verbose_name="タイトル", max_length=200)
    content = models.TextField(verbose_name="内容")
    description = models.TextField(blank=True, default="")
    image = models.ImageField(upload_to="images/uploaded/", default=None, null=True, blank=True)
    detail_main = ImageSpecField(
        source="image", processors=[ResizeToFill(640, 480)], format="jpeg", options={"quality": 80}
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "レシピ"
        verbose_name_plural = "レシピ"

    def __str__(self):
        return self.title

staffroom/models.py
from django.db import models

# Create your models here.

comment/forms.py
from django import forms

from comment.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
            "recipe",
        ]
        widgets = {"recipe": forms.HiddenInput()}
        labels = {"content": "コメントをどうぞ"}

recipe/forms.py
from django import forms

from .models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = [
            "title",
            "content",
            "description",
            "image",
            "user",
        ]
        widgets = {"user": forms.HiddenInput()}

comment/views.py
from django.contrib import messages
from django.shortcuts import redirect

from comment.forms import CommentForm


def comment_create(request):
    recipe_id = request.POST.get("recipe")
    content = request.POST.get("content")
    data = {"content": content, "recipe": recipe_id}
    form = CommentForm(data=data)
    if form.is_valid():
        form.save()
        messages.success(request, "コメントを投稿しました。")
    else:
        messages.error(request, "コメントが投稿できませんでした")
    return redirect("recipe:detail", pk=recipe_id)

lib/views.py
from django.views.generic import TemplateView

from recipe.models import Recipe


class IndexTemplateView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["recipe_list"] = Recipe.objects.order_by("-created")
        try:
            context["recipe_top"] = Recipe.objects.order_by("?")[0]
        except IndexError:
            context["recipe_top"] = None
        return context

recipe/views.py
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView

from comment.forms import CommentForm

from .models import Recipe


class RecipeListView(ListView):
    model = Recipe
    template_name = "recipe/recipe_list.html"

    def get_queryset(self):
        qs = Recipe.objects.all()
        keyword = self.request.GET.get("q")
        if keyword:
            qs = qs.filter(title__contains=keyword)
        return qs


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipe/recipe_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["CommentForm"] = CommentForm(initial={"recipe": self.object})
        return context

staffroom/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, TemplateView, UpdateView

from recipe.forms import RecipeForm
from recipe.models import Recipe


class StaffroomMixin(LoginRequiredMixin):
    login_url = reverse_lazy("login")


class StaffroomTemplateView(StaffroomMixin, TemplateView):
    template_name = "staffroom/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["recipe_list"] = Recipe.objects.filter(user=self.request.user).prefetch_related("comment_set")
        else:
            context["recipe_list"] = None
        return context


class RecipeCreateView(StaffroomMixin, CreateView):
    model = Recipe
    form_class = RecipeForm
    template_name = "recipe/recipe_form.html"
    # fields = ["title", "content", "description", "image"]
    success_url = reverse_lazy("recipe:index")

    def post(self, request, *args, **kwargs):
        user = request.user
        data = request.POST.dict()
        data["user"] = user.id
        form = RecipeForm(data=data, files=request.FILES)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        messages.success(self.request, "保存しました")
        return super().form_invalid(form)

    def form_invalid(self, form):
        messages.error(self.request, "保存できませんでした")
        return super().form_invalid(form)


class RecipeUpdateView(StaffroomMixin, UpdateView):
    model = Recipe
    template_name = "recipe/recipe_form.html"
    fields = ["title", "content", "description", "image"]

    def get_success_url(self):
        pk = self.kwargs.get("pk")
        return reverse("recipe:detail", kwargs={"pk": pk})

    def form_valid(self, form):
        messages.success(self.request, "更新しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "更新できませんでした")
        return super().form_invalid(form)


class RecipeDeleteView(StaffroomMixin, DeleteView):
    model = Recipe
    template_name = "recipe/recipe_confirm_delete.html"
    success_url = reverse_lazy("recipe:index")

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "削除しました")
        return super().delete(request, *args, **kwargs)

lib/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>レシピ投稿サイト レシピポスト - Recipe Post</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/small-business.css' %}" rel="stylesheet">
</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">レシピポスト</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recipe:index' %}">レシピ</a>
          </li>
        </ul>
      </div>
      <form class="form-inline" action="{% url 'recipe:index' %}">
        <input class="form-control mr-sm-2" name="q" value="{{ request.GET.q }}" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div> <!-- end container -->
  </nav>

  <!-- Page Content -->
  <div class="container">
  {% if messages %}
    {% for message in messages %}
      <div {% if message.tags %} class="my-3 alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" {% endif %} role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  {% endif %}
  {% block body %}
  {% endblock %}
  </div> <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark mt-3">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Recipe Post 2021</p>
    </div> <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

lib/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block body %}
  <!-- Heading Row -->
  <div class="row align-items-center my-5">
    <div class="col-lg-7">
    {% if recipe_top.image %}
      <img class="img-fluid rounded mb-4 mb-lg-0" src="{{ recipe_top.image.url }}" alt="">
    {% else %}
      <img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'images/01.jpg' %}" alt="">
    {% endif %}
    </div>
    <div class="col-lg-5">
      <h1 class="font-weight-light">{{ recipe_top.title }}</h1>
      <p>{{ recipe_top.description }}</p>
      {% if recipe_top %}
      <a class="btn btn-primary" href="{% url 'recipe:detail' recipe_top.id %}">詳細</a>
      {% endif %}
    </div>
  </div>

  <!-- Call to Action Well -->
  <div class="card text-white bg-secondary my-5 py-4 text-center">
    <div class="card-body">
      <p class="text-white m-0">This call to action card is a great place to showcase some important information or display a clever tagline!</p>
    </div>
  </div>

  <!-- Content Row -->
  <div class="row">
  {% for recipe in recipe_list %}
    <div class="col-md-4 mb-5">
      <div class="card h-100">
      {% if recipe.image %}
        <img class="card-img-top" src="{{ recipe.image.url }}" alt="{{ recipe.title }}"/>
      {% else %}
        <img class="card-img-top" src="{% static 'images/01.jpg' %}" alt="{{ recipe.title }}"/>
      {% endif %}
        <div class="card-body">
          <h2 class="card-title">{{ recipe.title }}</h2>
          <p class="card-text">{{ recipe.description }}</p>
        </div>
        <div class="card-footer">
          <a href="{% url 'recipe:detail' recipe.id %}" class="btn btn-primary btn-sm">詳しく見る</a>
        </div>
      </div>
    </div>
  {% endfor %}
  </div> <!-- /.row -->
{% endblock %}

lib/templates/login.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>ログイン - Recipe Post</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header">
                                        <h3 class="text-center font-weight-light my-4">ログイン</h3>
                                    </div>
                                    <div class="card-body">
                                        <form method="post">{% csrf_token %}
                                            {{ form|crispy }}
                                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <button class="btn btn-primary">ログイン</button>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center">
                                        <div class="small"><a href="register.html">Need an account? Sign up!</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2020</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

lib/templates/logout.html
{% extends "base.html" %}
{% block body %}
    <h1>ログアウトしました</h1>
{% endblock %}

recipe/templates/recipe/recipe_confirm_delete.html
{% extends "base.html" %}
{% block body %}
  <div class="my-5">
    <div class="row">
      <div class="col">
        <form method="post">{% csrf_token %}
          <p class="bg-danger text-white p-3">本当に削除してよろしいですか？</p>
          <button type="submit" class="btn btn-danger">削除</button>
          <a href="{% url 'recipe:detail' recipe.id %}" class="btn btn-secondary">キャンセル</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

recipe/templates/recipe/recipe_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
  <div class="row my-3">
    <div class="col-lg-12">
      <h1>{{ recipe.title }}</h1>
    </div>
    <div class="col-lg-7">
    {% if recipe.image %}
      <img src="{{ recipe.detail_main.url }}" width="640" class="img-fluid rounded border">
    {% else %}
      <img src="{% static 'images/01.jpg' %}" width="640" class="img-fluid rounded border">
    {% endif %}
    </div>
    <div class="col-lg-5">
      <h3>作り方</h3>
      <p>{{ recipe.content }}</p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <h3>このレシピの説明</h3>
      <p>{{ recipe.description }}</p>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col">
      <p class="text-muted">投稿日：{{ recipe.created }}</p>
    </div>
    <div class="col">
      <p class="text-muted">変更日：{{ recipe.modified }}</p>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h3>コメント</h3>
      <ul class="list-unstyled">
      {% for comment in recipe.comment_set.all %}
        <li class="border-bottom mt-2">{{ comment.content }} -- ({{ comment.created }})</li>
      {% endfor %}
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <form method="post" action="{% url 'comment:create' %}">{% csrf_token %}
        {{ CommentForm|crispy }}
        <button type="submit" class="btn btn-primary">送信</button>
      </form>
    </div>
  </div>
  {% if request.user.is_authenticated and request.user == recipe.user %}
  <hr>
  <div class="row">
    <div class="col-lg-12">
      <a class="btn btn-info" href="{% url 'staffroom:recipe:update' recipe.id %}">編集</a>
      <a class="btn btn-danger" href="{% url 'staffroom:recipe:delete' recipe.id %}">削除</a>
    </div>
  </div>
  {% endif %}
{% endblock %}

recipe/templates/recipe/recipe_list.html
{% extends "base.html" %}
{% load static %}
{% load imagekit %}
{% block body %}
  <h1>レシピ一覧</h1>
  {% for recipe in recipe_list %}
    <div class="media">
    {% if recipe.image %}
      {% thumbnail "120x90" recipe.image -- class="align-self-center mr-3" %}
    {% else %}
      <img src="{% static 'images/01.jpg' %}" class="align-self-center mr-3" alt="..." width="120">
    {% endif %}
      <div class="media-body">
        <a href="{% url 'recipe:detail' recipe.id %}">
          <h5 class="mt-0">{{ recipe.title }}</h5>
        </a>
        <p>{{ recipe.description }}</p>
      </div>
    </div>
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

staffroom/templates/recipe/recipe_confirm_delete.html
{% extends "staffroom.html" %}
{% block body %}
  <div class="my-5">
    <div class="row">
      <div class="col">
        <form method="post">{% csrf_token %}
          <p class="bg-danger text-white p-3">本当に削除してよろしいですか？</p>
          <button type="submit" class="btn btn-danger">削除</button>
          <a href="{% url 'recipe:detail' recipe.id %}" class="btn btn-secondary">キャンセル</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

staffroom/templates/recipe/recipe_form.html
{% extends "staffroom.html" %}
{% load crispy_forms_tags %}
{% block breadcrumbs %}
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item">Dashboard</li>
    <li class="breadcrumb-item">レシピ</li>
    <li class="breadcrumb-item">新規作成</li>
  </ol>
{% endblock %}
{% block body %}
<div class="row my-3">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
          {{ form|crispy }}
          <div class="row">
            <div class="col">
              <button type="submit" class="btn btn-primary">保存</button>
              {% if not "create" in request.path %}
              <a href="{% url 'recipe:detail' recipe.id %}" class="btn btn-secondary">キャンセル</a>
              {% endif %}
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

staffroom/templates/staffroom.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - SB Admin</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <a class="navbar-brand" href="index.html">Recipe Post</a>
            <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="#">Settings</a>
                        <a class="dropdown-item" href="#">Activity Log</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">ログアウト</a>
                    </div>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="{% url 'staffroom:index' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <div class="sb-sidenav-menu-heading">レシピ</div>
                            <a class="nav-link" href="{% url 'staffroom:recipe:create' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                新規作成
                            </a>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        {{ request.user.username }}
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid">
                        <h1 class="mt-4">Dashboard</h1>
                        {% block breadcrumbs %}
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Dashboard</li>
                        </ol>
                        {% endblock %}
                        {% block body %}
                        {% endblock %}
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Recipe Post 2023</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/chart-area-demo.js"></script>
        <script src="assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'assets/demo/datatables-demo.js' %}"></script>
    </body>
</html>

staffroom/templates/staffroom/index.html
{% extends 'staffroom.html' %}
{% block body %}
<div class="col-lg-12">
  <div class="card">
    <div class="card-header">
      レシピ一覧
    </div>
    <div class="card-body">
      <table class="table">
      {% for recipe in recipe_list %}
        <tr>
          <th>{{ recipe.title }}</th>
          <th>
            <a href="{% url 'recipe:detail' recipe.id %}" class="btn btn-primary">詳細</a>
            <a href="{% url 'staffroom:recipe:update' recipe.id %}" class="btn btn-secondary">編集</a>
          </th>
        </tr>
      {% endfor %}
      </table>
    </div>
  </div>
  <div class="card mt-3">
    <div class="card-header">
      コメント
    </div>
    <div class="card-body">
      <table class="table">
        <thead>
          <tr>
            <th>レシピ</th>
            <th>コメント内容</th>
            <th>コメント投稿日</th>
          </tr>
        </thead>
        <tbody>
        {% for recipe in recipe_list %}
          {% for comment in recipe.comment_set.all %}
          <tr>
            <td>{{ recipe.title }}</td>
            <td>{{ comment.content }}</td>
            <td>{{ comment.created }}</td>
          </tr>
          {% endfor %}
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}